apiVersion: v1
data:
  LIBRENMS_SNMP_COMMUNITY: librenmsdocker
  LIBRENMS_WEATHERMAP: "false"
  LIBRENMS_WEATHERMAP_SCHEDULE: '*/5 * * * *'
  LOG_IP_VAR: remote_addr
  MEMORY_LIMIT: 256M
  DB_HOST: db.librenms.svc.cluster.local
  DB_PORT: "3306"
  DB_TIMEOUT: "60"
  DB_PASSWORD: asupersecretpassword
  DB_NAME: librenms
  OPCACHE_MEM_SIZE: "128"
  PGID: "1000"
  PUID: "1000"
  REAL_IP_FROM: 0.0.0.0/32
  REAL_IP_HEADER: X-Forwarded-For
  TZ: America/New_York
  UPLOAD_MAX_SIZE: 16M
  REDIS_HOST: redis.librenms.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DB: "0"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: librenms-librenms-env
  name: librenms-env
---
apiVersion: v1
data:
  MYSQL_DATABASE: librenms
  MYSQL_PASSWORD: asupersecretpassword
  MYSQL_USER: librenms
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  TZ: America/New_York
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: librenms-db-env
  name: librenms-db-env